name: jq
version: 0.1.0

homepage: https://github.com/sshine/hs-jq
author: Simon Shine
maintainer: shreddedglory@gmail.com
copyright: 2019-2024 Simon Shine
extra-source-files:
  - README.md

dependencies:
  - base
  - megaparsec
  - parser-combinators
  - scientific
  - text
  - mtl

default-extensions:
  - OverloadedStrings

library:
  exposed-modules:
    - Jq
    - Jq.Expr
    - Jq.Number
    - Jq.Parser
  source-dirs: src

executables:
  jq:
    source-dirs: app
    main: Main.hs

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - jq
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - hspec
      - hspec-megaparsec
      - raw-strings-qq
      - aeson
      - containers
      - vector

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    dependencies:
      - jq
      - criterion
    ghc-options: -O2
